repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=99000]
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]

  - repo: https://github.com/google/pre-commit-tool-hooks
    rev: v1.2.5  # Use the rev you want to point at.
    hooks:
      - id: markdown-toc

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        exclude: '^\.venv/'  # Exclude the .venv directory
        args: ["-r", "."]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  -   repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.10.0
      hooks:
      -   id: shellcheck
          args: ['--shell=bash']  # Adjust this if you're using a different shell

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-1
    hooks:
      # Choose one of:
      - id: shfmt         # native (requires/installs Go to build)
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.96.1"
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate
      - id: terraform_tfsec
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
    - id: markdownlint
