# Scans for basic issues such as trailing spaces, file endings, and merges conflicts.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=99000]
      - id: check-symlinks
      - id: check-toml
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-executables-have-shebangs  # Ensures scripts have shebangs for executables

# Python linter and fixer using ruff (linter and formatter).
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]

# Tool to generate a table of contents for markdown files.
  - repo: https://github.com/google/pre-commit-tool-hooks
    rev: v1.2.5
    hooks:
      - id: markdown-toc

# Security scan for Python code using Bandit.
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.10
  #   hooks:
  #     - id: bandit
  #       exclude: '^\.venv/'  # Exclude the .venv directory
  #       args: ["-r", "."]

# Detect secrets in code to avoid committing sensitive information.
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

# Shell script formatting and linting using Shellcheck and shfmt.
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ['--shell=bash']  # Adjust this if you're using a different shell (bash, sh, zsh)

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.10.0-1
    hooks:
      - id: shfmt  # Formats shell scripts for consistent structure

# Terraform linters and formatters for infrastructure as code.
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.24
    hooks:
      - id: tflint
      - id: terraform-validate   # Validates Terraform configuration
      - id: terraform-fmt        # Automatically formats Terraform files

# Terraform-specific docs and security checks.
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_docs       # Automatically generates documentation for Terraform modules
      - id: terraform_checkov              # Performs security checks for Terraform infrastructure

# Lint markdown files for consistency and correctness.
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
